# Generated by Django 5.2.5 on 2025-09-27 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='duration',
            field=models.CharField(blank=True, choices=[('3_DAYS', '3 days'), ('5_DAYS', '5 days'), ('1_WEEK', '1 week'), ('10_DAYS', '10 days'), ('2_WEEKS', '2 weeks')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
