# Generated by Django 5.2.5 on 2025-09-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0002_itinerary_created_at_itinerary_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
