# Generated by Django 5.2.5 on 2025-09-30 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0003_itinerary_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='preferences',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_by', to='personalize.interest'),
        ),
    ]
