# Generated by Django 5.2.5 on 2025-09-30 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0004_remove_userpreference_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferences',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_by', to='personalize.interest'),
            preserve_default=False,
        ),
    ]
