# Generated by Django 5.2.5 on 2025-10-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0006_alter_userpreference_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='destination',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destination_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
