# Generated by Django 5.2.5 on 2025-10-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0008_alter_itinerary_destination_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='destination_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
