# Generated by Django 5.2.5 on 2025-10-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0009_alter_itinerary_destination_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='latitude',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='longitude',
            field=models.CharField(),
        ),
    ]
