# Generated by Django 5.2.5 on 2025-10-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0011_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
