# Generated by Django 5.2.5 on 2025-10-02 09:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0012_alter_place_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DaySpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('place_name', models.CharField(blank=True, max_length=255, null=True)),
                ('place_location', models.CharField(blank=True, max_length=255, null=True)),
                ('place_image', models.URLField(blank=True, null=True)),
                ('place_type', models.CharField(blank=True, max_length=255, null=True)),
                ('place_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('place_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='personalize.day')),
            ],
        ),
        migrations.DeleteModel(
            name='TouristSpot',
        ),
    ]
