# Generated by Django 5.2.5 on 2025-10-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0013_day_created_at_day_updated_at_dayspot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='visit_date',
            field=models.DateField(default=2000),
            preserve_default=False,
        ),
    ]
