# Generated by Django 5.2.5 on 2025-10-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0014_day_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
